"""Guard the rule that every number quoted in the docs is reproducible.

These tests do not re-run the models (that needs the trained artefacts). They
check the two things that actually break in practice: that the documented
commands point at scripts that exist, and that the results tables the README
quotes were generated by the harness rather than typed by hand.
"""

from __future__ import annotations

import os
import re

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

COMMANDS = [
    "scripts/download_data.py",
    "scripts/build_dataset.py",
    "scripts/check_leakage.py",
    "scripts/train_tfidf.py",
    "scripts/evaluate_models.py",
    "scripts/evaluate_with_ci.py",
    "scripts/benchmark_latency.py",
    "scripts/llm_cost.py",
    "scripts/make_test_candidates.py",
    "scripts/import_user_messages.py",
    "scripts/freeze_test.py",
    "scripts/generate_synthetic.py",
    "src/models/tfidf.py",
    "src/models/transformer.py",
    "src/models/llm_prompted.py",
    "src/models/lora.py",
]

CONFIGS = [
    "configs/indicbertv2.json",
    "configs/xlmr.json",
    "configs/lora_smollm135m.json",
]


@pytest.mark.parametrize("relative", COMMANDS + CONFIGS)
def test_documented_command_exists(relative):
    assert os.path.exists(os.path.join(REPO_ROOT, relative)), f"{relative} is documented but missing"


def test_readme_quotes_a_regenerated_number():
    """The README's headline F1 must match the harness output, not a hand-typed value."""
    results_json = os.path.join(REPO_ROOT, "results", "model_comparison.json")
    readme = open(os.path.join(REPO_ROOT, "README.md"), encoding="utf-8").read()
    if not os.path.exists(results_json):
        pytest.skip("no evaluation output present; run scripts/evaluate_models first")
    import json

    payload = json.load(open(results_json, encoding="utf-8"))
    for result in payload["results"]:
        if result["model"] == "tfidf-lr":
            assert f"{result['f1']:.4f}" in readme, "README F1 for tfidf-lr is out of date"


def test_readme_has_no_unmarked_placeholders():
    readme = open(os.path.join(REPO_ROOT, "README.md"), encoding="utf-8").read()
    for placeholder in ("YOUR_USERNAME", "TBD", "XXX%", "F1.0000", "9.9999"):
        assert placeholder not in readme, f"placeholder left in README: {placeholder}"


def test_docs_state_how_each_number_is_produced():
    doc = open(os.path.join(REPO_ROOT, "docs", "model_comparison.md"), encoding="utf-8").read()
    assert re.search(r"python -m scripts\.\w+", doc), "model comparison doc quotes no commands"
    assert "does not settle" in doc, "model comparison doc must state what it does not show"
